### ISSUE TITLE
Azure login process

### ISSUE THREAD

**Issue by Quilbeast** [renzska/GoogleSignInForms#1]
I'm having trouble getting your azure login process to work. It does seem to make a request, but I get the following error:

Microsoft.WindowsAzure.MobileServices.MobileServiceInvalidOperationException: The request could not be completed.  (Unauthorized)

Do you have a clue what this could be?

**Comment by renzska** [comment]
This sample does not include the code for authorizing to Azure. You'll need to use the LoginAsync method provided in their MobileClient for that to work.

Here's an example:

```
MobileServiceClient.LoginAsync(provider, jToken);
```
The example starts here: https://github.com/renzska/GoogleSignInForms/blob/master/iOS/Renderers/GoogleSignInPageRenderer.cs#L41

Here's also an example from Xamarin:
https://developer.xamarin.com/guides/xamarin-forms/web-services/authentication/azure/

And here's the source for that article:
https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoAzureAuth
